name: flutter_api_images
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-191.0.dev <4.0.0'


# lib add here
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
# provider
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1
  google_sign_in: ^6.1.5
  path_provider: ^2.1.1

# tools
  http: ^1.1.0
  image_picker: ^1.0.4
# firebase
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_storage: ^11.2.7
  firebase_auth: ^4.10.0
  provider: ^6.0.5
  firebase_database: ^10.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_icons:
  android: true  # สร้างไอคอนสำหรับ Android
  image_path: "lib/assets/s.png"  # ตำแหน่งของไอคอนที่คุณต้องการ

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
